spring.application.name=RetailStore-Feedback

gemini.api-key=AIzaSyDahNxcWwWwIQZUys3cY_tNOByLNkyhl9s
gemini.api-url="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

# Logging configuration
logging.level.com.retailstore=DEBUG
logging.level.org.springframework.web=INFO

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML